using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Embeder;

internal static class Program
{
    private static void Main(string[] args)
    {
        if (args.Length < 2)
        {
            ShowUsage();
            return;
        }

        var fileMappings = new List<FileMapping>();
        var outputPath = "EmbeddedFiles.cs";
        var className = "EmbeddedResources";
        var namespaceName = "Embedded";

        for (var i = 0; i < args.Length; i++)
        {
            var arg = args[i];

            switch (arg)
            {
                case not null when arg.StartsWith("--file=") || arg.StartsWith("-f="):
                {
                    var mapping = arg[(arg.IndexOf('=') + 1)..];
                    fileMappings.AddFileMapping(mapping);

                    break;
                }
                case "--file" or "-f":
                {
                    if (i + 1 < args.Length)
                    {
                        fileMappings.AddFileMapping(args[++i]);
                    }

                    break;
                }
                case "--output" or "-o" when i + 1 < args.Length:
                    outputPath = args[++i];
                    break;
                case "--class" or "-c" when i + 1 < args.Length:
                    className = args[++i];
                    break;
                case "--namespace" or "-n" when i + 1 < args.Length:
                    namespaceName = args[++i];
                    break;
                default:
                {
                    if (arg != null && arg.Contains(':'))
                    {
                        fileMappings.AddFileMapping(arg);
                    }

                    break;
                }
            }
        }

        if (fileMappings.Count == 0)
        {
            Console.WriteLine("Error: No files specified for embedding.");
            ShowUsage();
            return;
        }

        var code = GenerateCode(fileMappings, className, namespaceName);

        File.WriteAllText(outputPath, code);

        Console.WriteLine($"Successfully generated {outputPath} with {fileMappings.Count} embedded file(s).");
    }

    private static void AddFileMapping(this List<FileMapping> fileMappings, string mapping)
    {
        var parts = mapping.Split([':', '='], 2);

        if (parts.Length != 2)
        {
            Console.WriteLine(
                $"Warning: Invalid file mapping format '{mapping}'. Use 'file_path:field_name' or 'file_path=field_name'");
            return;
        }

        var filePath = parts[0];
        var fieldName = parts[1];

        if (!File.Exists(filePath))
        {
            Console.WriteLine($"Warning: File not found '{filePath}'. Skipping.");
            return;
        }

        fileMappings.Add(new FileMapping(filePath, fieldName));
    }

    private static void ShowUsage()
    {
        Console.WriteLine("FileEmbedder - Utility to embed files as byte arrays in C# code");
        Console.WriteLine("Usage:");
        Console.WriteLine("  FileEmbedder [options] <file1:field1> [file2:field2] ...");
        Console.WriteLine();
        Console.WriteLine("Options:");
        Console.WriteLine("  -f, --file <file:field>    Add a file to embed (can be used multiple times)");
        Console.WriteLine("  -o, --output <path>        Output file path (default: EmbeddedFiles.cs)");
        Console.WriteLine(
            "  -c, --class <name>         Class name for the generated code (default: EmbeddedResources)");
        Console.WriteLine("  -n, --namespace <name>     Namespace for the generated code (default: Embedded)");
        Console.WriteLine();
        Console.WriteLine("Examples:");
        Console.WriteLine("  FileEmbedder image.png:ImageData style.css:StyleContent -o Resources.cs");
        Console.WriteLine("  FileEmbedder --file logo.png:Logo --file config.json:ConfigData --output AppResources.cs");
    }

    private static string GenerateCode(List<FileMapping> fileMappings, string className,
        string namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by FileEmbedder");
        sb.AppendLine("// Do not modify this file manually");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public static partial class {className}");
        sb.AppendLine("    {");

        foreach (var (filePath, fieldName) in fileMappings)
        {
            var bytes = File.ReadAllBytes(filePath);

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Embedded file: {Path.GetFileName(filePath)}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static readonly byte[] {fieldName} = new byte[{bytes.Length}] {{");

            for (var i = 0; i < bytes.Length; i += 12)
            {
                sb.Append("            ");

                for (var j = 0; j < 12 && i + j < bytes.Length; j++)
                {
                    sb.Append($"0x{bytes[i + j]:X2}, ");
                }

                sb.AppendLine();
            }

            sb.AppendLine("        };");
            sb.AppendLine();
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private record FileMapping(string FilePath, string FieldName);
}
